
logging:
  level:
    org.springframework.security: WARN
server:
  port: 8080
spring:
  resources:
    chain:
      enabled: true
management:
  security:
    enabled: true # set to false to disable 'default' Spring Boot security